Update main.yml
Syncing the main branch's main.yml with the terraform_testing main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,7 +1,13 @@
 name: Update AWS Environment
 run-name: ${{ github.actor }} is updating the AWS environment in GitHub Actions 🚀
 
-on: [push]
+on: 
+  push:
+    branches:
+      - main
+
+permissions:
+  contents: read
 
 jobs:
   update-infra-and-sync-site: #updates AWS infrastructure and syncs S3 bucket changes
@@ -12,21 +18,57 @@ jobs:
       working_directory: ./terraform
     permissions:
       id-token: write # This is required for requesting the JWT
-      contents: read  # This is required for actions/checkout
     steps: 
+      - name: Harden Runner
+        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
+        with:
+          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
+
       - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v2
+        uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef # v2.0.0
         with:
           aws-region: us-east-1
           role-to-assume: ${{ secrets.WRITE_ROLE }}
           role-session-name: OIDCSession
       - name: Download repo
-        uses: actions/checkout@v3
-      - name: Terraform init, plan and apply
-        working-directory: ${{ env.working_directory }}
+        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
+#       - name: Build SAM template for deployment 
+#         run: sam build
+#       - name: Deploy SAM template to AWS
+#         run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --debug
+      - name: Copy files to the production website with the AWS CLI
         run: |
-          echo `pwd`
-          terraform init
-          terraform fmt -check
-          terraform plan
-          terraform apply -auto-approve     
+          aws s3 sync . s3://gb-cloud-resume --size-only --exclude='*' --include='*.html' --include='*.css' --include='*.js' --include='*.png' --include='*.ico' --include='*.webmanifest'
+#       - name: Check deployment status
+#         run: aws cloudformation describe-stacks --stack-name cloud-resume-challenge || exit 1
+#       - name: Terraform init, plan and apply
+#         working-directory: ${{ env.working_directory }}
+#         run: |
+#           echo `pwd`
+#           terraform init
+#           terraform fmt -check
+#           terraform plan
+#           terraform apply -auto-approve     
+
+      
+  dast-scan: #performs Dynamic Application Security Testing against the target site
+    runs-on: ubuntu-latest
+    needs: update-infra-and-sync-site
+    container:
+      image: owasp/zap2docker-stable
+      options: --user root -v ${{ github.workspace }}:/zap/wrk/:rw
+    steps:
+      - name: Harden Runner
+        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
+        with:
+          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
+
+      - name: Run ZAP baseline scan
+        run: |
+          zap-baseline.py -t https://grahambaggett.com -r report_html.html -a || echo 0
+      - name: Upload ZAP report
+        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
+        with:
+            name: DAST_Report.html
+            path: ./report_html.html
+      
